name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install GCC
      run: sudo apt update && sudo apt install -y gcc

    - name: Build C program
      run: gcc test.c variables_of_projects.c -o myprogram

    - name: Run C program
      run: ./myprogram
